# ========================================================
# 机器学习诊断模型分析代码（张猛，2026-09）
# ========================================================
setwd('/home/zm3028/research_platform/ZJ1/DR_bioinfo_paper')
library(glmnet)
library(randomForest)
library(e1071)
library(pROC)
data_list <- readRDS('03_rds/step04_final_data_for_ml.rds')
expr_mat <- t(data_list$expr[c('FTH1','LDHA','CTSZ'), ])
labels <- data_list$labels
set.seed(123)
cv_lasso <- cv.glmnet(expr_mat, labels, family = 'binomial', alpha = 1)
set.seed(123)
rf_model <- randomForest(x = expr_mat, y = as.factor(labels), ntree = 500, importance = TRUE)
set.seed(123)
svm_model <- svm(x = expr_mat, y = as.factor(labels), probability = TRUE)
pred_lasso <- as.numeric(predict(cv_lasso, newx = expr_mat, s = 'lambda.min', type = 'response'))
roc_lasso <- roc(labels, pred_lasso)
core_expr <- readRDS('03_rds/step12_gse160306_core_expr.rds')
labels_ext <- c(rep(1, 39), rep(0, 20))
score <- colMeans(core_expr)
roc_ext <- roc(labels_ext, score)
cat('GSE160306 AUC =', round(auc(roc_ext), 3), '\n')
core_expr_60436 <- readRDS('03_rds/step12_gse60436_core_expr.rds')
labels_60436 <- c(rep(0, 3), rep(1, 6))
score_60436 <- colMeans(core_expr_60436)
roc_60436 <- roc(labels_60436, score_60436)
cat('GSE60436 AUC =', round(auc(roc_60436), 3), '\n')
